FROM node:18-slim

WORKDIR /app

COPY package.json tsconfig.json ./

RUN apt-get update -y && apt-get install -y openssl

RUN npm install -g typescript ts-node

RUN npm install -g prisma

RUN npm install

COPY prisma/schema.prisma ./prisma/

COPY ./ ./

RUN npx prisma generate

RUN npm run build

CMD ["npm", "start"]
